name: unit4_assignment_canete
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/image/profile1.png
    - lib/image/profile2.jpg
    - lib/image/profile3.jpg
    - lib/image/profile4.jpg
    - lib/image/profile5.jpg

  fonts:
    - family: Helvetica
      fonts:
        - asset: lib/fonts/HELVETICA.TTF
